name: Build UPBGE BinaryCrypt

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      UPBGE_BINARYCRYPT_PASSWORD: ${{ runner.temp }}/pw
      UPBGE_BINARYCRYPT_SALT: ${{ runner.temp }}/salt

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y cmake build-essential pkg-config libraylib-dev libgl1-mesa-dev openssl

      - name: Install Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install cmake openssl -y

      - name: Generate Random Password and Salt
        shell: bash
        run: |
          echo "UPBGE_BINARYCRYPT_PASSWORD=$(openssl rand -hex 32)" >> $GITHUB_ENV
          echo "UPBGE_BINARYCRYPT_SALT=$(openssl rand -hex 16)" >> $GITHUB_ENV

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build
